name: Test-Script

on:
  push:         {branches: [dev]}
  pull_request: {branches: [dev]}



jobs:
  build:

    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v2



    - name: Test flawless run
      run: |
      chmod +x "${GITHUB_WORKSPACE}/installer.sh"
      "${GITHUB_WORKSPACE}/installer.sh"





