name: Run script

on:
  push:         {branches: [dev]}
  pull_request: {branches: [dev]}



jobs:
  build:

    runs-on: ubuntu-latest
   

    steps:
    - uses: actions/checkout@v2



    - name: Run script
      run: |
       chmod +x installer.sh
       bash installer.sh


